### PR TITLE
Add babel and transpile to es5

### PR DESCRIPTION
**Pull request by andycloke**
Firstly, awesome library! 

I tried to use it in a node project and it didn't work because it uses ES6 syntax, so I added babel and transpiled down to es5. Other changes: add missing `hash-to-array` dependency. Add `package-lock.json`. Add `.gitignore`.

### CODE REVIEW

**Comment by benbucksch** [comment]
Hi Andy, I'm glad you like the project and it's useful for you!

node supports ES6 syntax, and in fact we're using it in node as well.

> in a node project ... it didn't work because it uses ES6 syntax

Can you tell me more? Which version of node are you using? Or are you forcing ES5 for some other, historic reason in your project, even though your node supports ES6?

**Comment by benbucksch** [comment]
> Add package-lock.json

FWIW, this is going to generate a warning for `yarn` users.

**Comment by benbucksch** [comment]
I've added the dependency and the `.gitignore`. Indeed, I forgot them. Thanks for telling me!

I am trying to keep git commits mostly atomic. Sorry that this creates conflicts for you now. They should be trivial to resolve, though.

**Comment by andycloke** [comment]
> Can you tell me more? Which version of node are you using? Or are you forcing ES5 for some other, historic reason in your project, even though your node supports ES6?

yeah exactly that - I am forced to use ES5. I think most packages ship ES5 for cases like this, but I appreciate that is changing now node supports ES6. 

I've actually found a different package now, so I don't need these changes. I'm happy to close the PR unless you want me to fix + merge?

**Comment by benbucksch** [comment]
> I am forced to use ES5

As far as I'm aware, you can mix ES5 and ES6 in node, [since node.js v6](https://node.green/), released 2016. I'd be curious to know, if there's a case which doesn't allow that.

**Pull request closed without merging**
